#cloud-config
package_update: true
package_upgrade: true

runcmd:
  # Create runner directories
  - mkdir -p /home/adminuser/actions-runner
  - mkdir -p /home/adminuser/actions-runner2

  # Set correct ownership
  - chown -R adminuser:adminuser /home/adminuser/actions-runner
  - chown -R adminuser:adminuser /home/adminuser/actions-runner2

  # Download runner binaries
  - curl -o /home/adminuser/actions-runner/actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
  - curl -o /home/adminuser/actions-runner2/actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz

  # Extract runners
  - tar xzf /home/adminuser/actions-runner/actions-runner-linux-x64-2.323.0.tar.gz -C /home/adminuser/actions-runner
  - tar xzf /home/adminuser/actions-runner2/actions-runner-linux-x64-2.323.0.tar.gz -C /home/adminuser/actions-runner2

  # Install required packages
  - apt install -y libssl-dev libicu-dev libkrb5-dev zlib1g libcurl4 openssl

  # Reapply permissions just in case
  - chown -R adminuser:adminuser /home/adminuser/actions-runner
  - chown -R adminuser:adminuser /home/adminuser/actions-runner2
  - chmod -R u+rwX /home/adminuser/actions-runner
  - chmod -R u+rwX /home/adminuser/actions-runner2

  # Configure the runners
  - su - adminuser -c '/home/adminuser/actions-runner/config.sh --unattended --url https://github.com/geresvb/backendrampup --token AJMGFBIO3KSF52NZVARSOU3H4RUX6'
  - su - adminuser -c '/home/adminuser/actions-runner2/config.sh --unattended --url https://github.com/geresvb/frontendrampup --token AJMGFBJ4SCMM3EMLLOFWOSTH4RUYK'

  # Start the runners in the background
  - su - adminuser -c 'nohup /home/adminuser/actions-runner/run.sh > /home/adminuser/actions-runner/runner.log 2>&1 &'
  - su - adminuser -c 'nohup /home/adminuser/actions-runner2/run.sh > /home/adminuser/actions-runner2/runner.log 2>&1 &'


#runcmd:
#  - mkdir home/adminuser/actions-runner
#  - curl -o /home/adminuser/actions-runner/actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
#  - tar xzf /home/adminuser/actions-runner/actions-runner-linux-x64-2.323.0.tar.gz -C /home/adminuser/actions-runner


#  - sudo apt-get install -y ca-certificates curl gnupg
#  - sudo mkdir -m 0755 -p /etc/apt/keyrings
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
#  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#  - sudo apt-get update -y
#  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#  - sudo usermod -aG docker adminuser
#  - sudo systemctl enable docker
#  - sudo systemctl start docker
#  - sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
#  - sudo chmod +x /usr/local/bin/docker-compose
#  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
#  - docker --version
 # - docker-compose --version
 # - sudo docker pull geresvb/frontend
