name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual execution

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_db_ssh_public_key: ${{ secrets.DB_SSH_PUBLIC_KEY }}
          TF_VAR_backend_ssh_public_key: ${{ secrets.BACKEND_SSH_PUBLIC_KEY }}
          TF_VAR_frontend_ssh_public_key: ${{ secrets.FRONTEND_SSH_PUBLIC_KEY }}
          TF_VAR_management_ssh_public_key: ${{ secrets.MANAGEMENT_SSH_PUBLIC_KEY }}

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_db_ssh_public_key: ${{ secrets.DB_SSH_PUBLIC_KEY }}
          TF_VAR_backend_ssh_public_key: ${{ secrets.BACKEND_SSH_PUBLIC_KEY }}
          TF_VAR_frontend_ssh_public_key: ${{ secrets.FRONTEND_SSH_PUBLIC_KEY }}
          TF_VAR_management_ssh_public_key: ${{ secrets.MANAGEMENT_SSH_PUBLIC_KEY }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_db_ssh_public_key: ${{ secrets.DB_SSH_PUBLIC_KEY }}
          TF_VAR_backend_ssh_public_key: ${{ secrets.BACKEND_SSH_PUBLIC_KEY }}
          TF_VAR_frontend_ssh_public_key: ${{ secrets.FRONTEND_SSH_PUBLIC_KEY }}
          TF_VAR_management_ssh_public_key: ${{ secrets.MANAGEMENT_SSH_PUBLIC_KEY }}
